# [Choice] Debian / Ubuntu version: debian-10, debian-9
ARG VARIANT=bionic
FROM registry.mxcao.me/public/vscode/devcontainers/cpp:dev-${VARIANT}

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
